### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by KunalShivhare** [sophieloiz/brain-tissues-segmentation#2]
Can you provide the dataset??

**Comment by katjaq** [comment]
Hello @KunalShivhare . Thank you for your interest. The dataset comprises more than 1000 individual MRIs and hence is not included here. It is publicly available at http://preprocessed-connectomes-project.org/abide/download.html . 
Hope that helps.
@sophieloiz We could probably add the link to the ReadMe :)

**Comment by usharupni** [comment]
hi, can you please provide detail of how mask is created for the dataset

**Comment by sophieloiz** [comment]
Hello @usharupni,
After extracting the brain with BET (FSL), we used the tissue segmentation tool named FAST to create our masks and obtained 3 different files corresponding to :
- the CSF mask
- the WM mask
- the GM mask
